uMax=input('Maximum Voltu giriniz  ');
R=input('Direncin deðeri giriniz  ');
L=input('Bobinin deðerini giriniz  ');
w=2*pi*82;
xL=w*L;
c=input('Kondansatörün deðerini giriniz  ');
xC=1/(w*c);
j=90; % açý
z1=complex(R,xL*(cos(90)+j*sin(90)));
z2=complex(0,xC*(cos(-90)+j*sin(-90)));
zT=z1*z2/(z1+z2);
U=uMax*0.707
iMax = uMax/zT;
uOrt = 0.636*uMax
i = 0.707*iMax
iOrt = 0.636*iMax
Pr = U*U/R
Pc = U*U/xC
pL = U*U/xL
S = U*i
